server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mkprocsDB?serverTimezone=Asia/Seoul
    username: mkprocs
    password: mkprocs1234!@
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  resources:
    cache:
      period: 0
  devtools:
    restart:
      additional-paths: src/main/resources/static
    livereload:
      enabled: true