server:
  port: 8089

spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.sqlite.JDBC
    #url: jdbc:sqlite:db.sqlite3
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mkprocsDB
    username: mkprocs
    password: mkprocs1234!@

  jpa:
    #database-platform: org.hibernate.dialect.SQLiteDialect
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  resources:
    cache:
      period: 0

  devtools:
    restart:
      additional-paths: src/main/resources/static
    livereload:
      enabled: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: devsixt60@gmail.com
    password: nrajaumnhfmgkyqj
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000

  logging:
    level:
      org:
        springframework:
          security: DEBUG

root:
  loc-path: C:/Users/jinwoong/IdeaProjects/sixtdev/


file:
  excel-upload:
    path: python_modules/excel_parse/__excel/

python:
  modules:
    excel-parser: python_modules/excel_parse/excel_parser.py